//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPE3_HERCHARMOR
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPE3_BDD : DbContext
    {
        public PPE3_BDD()
            : base("name=PPE3_BDD")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<client> client { get; set; }
        public DbSet<emprunt> emprunt { get; set; }
        public DbSet<episode> episode { get; set; }
        public DbSet<film> film { get; set; }
        public DbSet<genre> genre { get; set; }
        public DbSet<saison> saison { get; set; }
        public DbSet<serie> serie { get; set; }
        public DbSet<support> support { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
